### Register - add new user and set cookie
POST http://localhost:3000/auth/register
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "username": "johndoe",
    "email": "jd@distnode.com",
    "password": "P@ssw0rd"
}

### Verification - get new verification email
GET http://localhost:3000/auth/verify-email
content-type: application/json

### Verification - verify email
POST http://localhost:3000/auth/verify-email?token=<>
content-type: application/json

### Password reset - get new reset email
GET http://localhost:3000/auth/password-reset?email=<>
content-type: application/json

### Password reset - apply password reset email
POST http://localhost:3000/auth/password-reset?token=<>
content-type: application/json

{
    "password": "NewP@ssw0rd"
}

### Login - get tokens and set in cookie
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "jd@distnode.com",
    "password": "P@ssw0rd"
}

### Refresh - update CSRF & access tokens using refresh token
GET http://localhost:3000/auth/refreshed-tokens

### Logout - invalidate cookies and delete current refresh token
POST http://localhost:3000/auth/logout
content-type: application/json

{}

### Get active refresh token ID for current user
GET http://localhost:3000/auth/refresh-token/current
Content-Type: application/json

### Get all refresh token IDs for current user
GET http://localhost:3000/auth/refresh-token/all
Content-Type: application/json

### Delete refresh token - overwrite cookies and delete refresh token
DELETE http://localhost:3000/auth/refresh-token/current
Content-Type: application/json

{}

### Delete all refresh tokens for active user
DELETE http://localhost:3000/auth/refresh-token/all
Content-Type: application/json

{}

### Delete user - remove user, overwrite cookies, and delete refresh tokens
DELETE http://localhost:3000/auth/user
Content-Type: application/json

{
    "email": "jd@distnode.com",
    "password": "P@ssw0rd",
    "csrfToken": "{{csrfToken}}"
}
